config/routes.rb
Rails.application.routes.draw do
  post 'home/command'
  post 'home/notify'
  get 'home/logs'
  get 'home/index'

  root 'home#index'
  #mount ActionCable.server => "/cable"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  def status_name
    status ? 'Turned On' : 'Turned Off'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token, only: :notify
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def command
    ActionCable.server.broadcast 'pi_commands_channel',
                                 command: params[:command]
    if params[:command] == 'turn_on'
      Log.create(status: true)
    else
      Log.create(status: false)
    end
    redirect_to root_path, notice: params[:command] == 'turn_on' ? 'Pump is on' : 'Pump is off'
  end

  def notify
    @log = Log.create(status: params[:status])
    NotifyMailer.with(log: @log).notification_email.deliver_now
  end

  def logs
    @logs = Log.all.order created_at: 'DESC'
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/command.html.erb
<h1>Home#command</h1>
<p>Find me in app/views/home/command.html.erb</p>

app/views/home/index.html.slim
.row
  .col.col-md-12
    .text-center
      h1 Welcome to Plant Watering System
      = link_to "Turn on the Pump",  home_command_path(command: 'turn_on'), method: :post, class: 'btn btn-success'
      = ' '
      = link_to "Turn off the Pump",  home_command_path(command: 'turn_off'), method: :post, class: 'btn btn-danger'

app/views/home/logs.html.slim
table.table.table-striped
  thead.thead-dark
    tr
      th Id
      th Status
      th Created At

  tbody
    - @logs.each do |log|
      tr
        td = log.id
        td = log.status_name
        td = log.created_at

app/views/home/notify.html.erb
<h1>Home#notify</h1>
<p>Find me in app/views/home/notify.html.erb</p>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Watering System"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"

    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Plant Watering System', root_path, class: 'navbar-brand'
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Logs", home_logs_path
              / li= link_to "Link 2", "/path2"
              / li= link_to "Link 3", "/path3"

    .container
      = bootstrap_flash
      = yield